"""add missing columns

Revision ID: 237810bf6517
Revises: 66e8d3861364
Create Date: 2026-03-24 11:23:48.146327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237810bf6517'
down_revision = '66e8d3861364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_bypass_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location_bypass_until')

    # ### end Alembic commands ###
