"""add badge_qr_tokens table

Revision ID: 4286f6fcf59f
Revises: 910cf079d791
Create Date: 2026-05-03 13:24:59.028692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4286f6fcf59f'
down_revision = '910cf079d791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_qr_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_badge_qr_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badge_qr_tokens'))
    )
    with op.batch_alter_table('badge_qr_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_qr_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_fee_payment_date')
        batch_op.drop_index('idx_fee_payment_user_date')

    op.drop_table('fee_payments')
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('applied_on',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('approved_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Unpaid'"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('paid_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('processed_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('earnings_last_updated',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('uq_payroll_user_period')
        batch_op.create_unique_constraint('uq_payroll_user_period', ['user_id', 'month', 'year'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('overtime_bypass_until',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('overtime_bypass_until',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payroll_user_period', type_='unique')
        batch_op.create_index('uq_payroll_user_period', ['user_id', 'month', 'year'], unique=1)
        batch_op.alter_column('earnings_last_updated',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('processed_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('paid_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Unpaid'"))

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.alter_column('approved_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('applied_on',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('fee_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount_paid', sa.FLOAT(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('revenue_id', sa.INTEGER(), nullable=True),
    sa.Column('recorded_by', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name='fk_fee_payments_recorded_by_users'),
    sa.ForeignKeyConstraint(['revenue_id'], ['revenues.id'], name='fk_fee_payments_revenue_id_revenues'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_fee_payments_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_fee_payments')
    )
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.create_index('idx_fee_payment_user_date', ['user_id', 'payment_date'], unique=False)
        batch_op.create_index('idx_fee_payment_date', ['payment_date'], unique=False)

    with op.batch_alter_table('badge_qr_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_qr_tokens_token'))

    op.drop_table('badge_qr_tokens')
    # ### end Alembic commands ###
