"""Add lockout_until and OT session tracking

Revision ID: 84dd632d5062
Revises: 4286f6fcf59f
Create Date: 2026-05-03 15:01:52.604045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dd632d5062'
down_revision = '4286f6fcf59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_end_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lockout_until')

    with op.batch_alter_table('overtime_requests', schema=None) as batch_op:
        batch_op.drop_column('actual_end_time')
        batch_op.drop_column('actual_start_time')

    # ### end Alembic commands ###
