"""add_is_viewed_to_login_token

Revision ID: 85af2ea614f1
Revises: e9cce5784f6c
Create Date: 2026-04-09 12:57:10.281909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85af2ea614f1'
down_revision = 'e9cce5784f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_viewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_column('is_viewed')

    # ### end Alembic commands ###
