"""Initial naming convention

Revision ID: 99ef6437efd7
Revises: 
Create Date: 2026-03-12 13:25:19.821297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ef6437efd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_allowed_locations')
    with op.batch_alter_table('allowed_locations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_blocked_ips_ip_address'), ['ip_address'])

    with op.batch_alter_table('contact_queries', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_contact_queries_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employee_profiles_employee_id'), ['employee_id'])

    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_login_tokens_token'), ['token'])

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.drop_column('base_pay')
        batch_op.drop_column('deductions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])

    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_verification_tokens_token'), ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_verification_tokens_token'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deductions', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('base_pay', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_login_tokens_token'), type_='unique')

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employee_profiles_employee_id'), type_='unique')

    with op.batch_alter_table('contact_queries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_queries_user_id_users'), type_='foreignkey')

    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_blocked_ips_ip_address'), type_='unique')

    with op.batch_alter_table('allowed_locations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_allowed_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('radius', sa.INTEGER(), server_default=sa.text('(100)'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
