"""Add auto-checkout and email reminder settings to OfficeSettings

Revision ID: af65110529a9
Revises: fe95f03ae96d
Create Date: 2026-04-08 15:57:35.380484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af65110529a9'
down_revision = 'fe95f03ae96d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_checkout_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_checkout_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('email_reminders_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_time_before_checkout', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office_settings', schema=None) as batch_op:
        batch_op.drop_column('reminder_time_before_checkout')
        batch_op.drop_column('email_reminders_enabled')
        batch_op.drop_column('auto_checkout_time')
        batch_op.drop_column('auto_checkout_enabled')

    # ### end Alembic commands ###
