"""add_browser_fingerprint_to_login_token

Revision ID: e9cce5784f6c
Revises: af65110529a9
Create Date: 2026-04-09 12:52:41.707513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cce5784f6c'
down_revision = 'af65110529a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser_fingerprint', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_tokens', schema=None) as batch_op:
        batch_op.drop_column('browser_fingerprint')

    # ### end Alembic commands ###
