"""Add target_user_id to Notice model

Revision ID: fe95f03ae96d
Revises: 237810bf6517
Create Date: 2026-04-07 10:13:14.711756

"""
from alembic import op
import sqlalchemy as sa
import database.models


# revision identifiers, used by Alembic.
revision = 'fe95f03ae96d'
down_revision = '237810bf6517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=50),
               type_=database.models.EncryptedType(length=255),
               existing_nullable=True)
        batch_op.alter_column('pan_number',
               existing_type=sa.VARCHAR(length=20),
               type_=database.models.EncryptedType(length=255),
               existing_nullable=True)
        batch_op.alter_column('personal_email',
               existing_type=sa.VARCHAR(length=120),
               type_=database.models.EncryptedType(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=database.models.EncryptedType(length=255),
               existing_nullable=True)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index('idx_leave_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notices_target_user_id_users'), 'users', ['target_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notices_target_user_id_users'), type_='foreignkey')
        batch_op.drop_column('target_user_id')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_user_status')

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=database.models.EncryptedType(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('personal_email',
               existing_type=database.models.EncryptedType(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('pan_number',
               existing_type=database.models.EncryptedType(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=database.models.EncryptedType(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
